<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="3" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="158993" started-at="2020-06-06T08:06:13Z" finished-at="2020-06-06T08:08:52Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="158993" started-at="2020-06-06T08:06:13Z" finished-at="2020-06-06T08:08:52Z">
      <class name="remoteTesting.dockerValidation.chromeTest1">
        <test-method status="PASS" signature="startDockerScale()[pri:0, instance:remoteTesting.dockerValidation.chromeTest1@3f2a3a5]" name="startDockerScale" is-config="true" duration-ms="33935" started-at="2020-06-06T08:06:13Z" finished-at="2020-06-06T08:06:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startDockerScale -->
        <test-method status="PASS" signature="test1()[pri:0, instance:remoteTesting.dockerValidation.chromeTest1@3f2a3a5]" name="test1" duration-ms="46323" started-at="2020-06-06T08:06:47Z" finished-at="2020-06-06T08:07:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="FAIL" signature="stopDockerDeleteFile()[pri:0, instance:remoteTesting.dockerValidation.chromeTest1@3f2a3a5]" name="stopDockerDeleteFile" is-config="true" duration-ms="45019" started-at="2020-06-06T08:08:03Z" finished-at="2020-06-06T08:08:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at remoteTesting.dockerValidation.stopDocker.stopFile(stopDocker.java:49)
at remoteTesting.dockerValidation.chromeTest1.stopDockerDeleteFile(chromeTest1.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.afterRun(TestRunner.java:725)
at org.testng.TestRunner.run(TestRunner.java:509)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopDockerDeleteFile -->
      </class> <!-- remoteTesting.dockerValidation.chromeTest1 -->
      <class name="remoteTesting.dockerValidation.chromeTest2">
        <test-method status="PASS" signature="test2()[pri:0, instance:remoteTesting.dockerValidation.chromeTest2@4cb2c100]" name="test2" duration-ms="63171" started-at="2020-06-06T08:06:47Z" finished-at="2020-06-06T08:07:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- remoteTesting.dockerValidation.chromeTest2 -->
      <class name="remoteTesting.dockerValidation.chromeTest3">
        <test-method status="PASS" signature="test3()[pri:0, instance:remoteTesting.dockerValidation.chromeTest3@6fb554cc]" name="test3" duration-ms="76438" started-at="2020-06-06T08:06:47Z" finished-at="2020-06-06T08:08:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
      </class> <!-- remoteTesting.dockerValidation.chromeTest3 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
